language: php

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4
    - nightly
    - hhvm

cache:
    directories:
        - $HOME/.composer/cache

matrix:
    allow_failures:
        - php: nightly
        - php: hhvm

before_script:
    - composer self-update
    - composer install --prefer-source --no-interaction -o

    - php --version
    - composer --version

script:
    - phpunit
