language: php

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4
    - 7.4snapshot

cache:
    directories:
        - $HOME/.composer/cache

matrix:
    allow_failures:
        - php: 7.4snapshot

before_script:
    - composer self-update
    - composer install --prefer-source --no-interaction -o

    - php --version
    - composer --version

script:
    - ./vendor/bin/phpunit
